Add table of icons
homarr-labs/dashboard-icons pull request #448
Opened 2023-07-31 23:52 UTC by jag-k

Fix #436 

Remove `TEMPLATE.md`, 'cause I reuse ICONS.md
Refactoring `ci.py`

You can see new `ICONS.md` in PR.

2023-08-01 00:01 UTC, jag-k commented on config/TEMPLATE.md
Remove `TEMPLATE.md`, 'cause I reuse `ICONS.md`

2023-08-10 08:16 UTC, walkxcode requested changes
Would it be possible to link the checkmark to the SVG version if it is available?

2023-08-10 13:47 UTC, jag-k commented
> Would it be possible to link the checkmark to the SVG version if it is available?

Yes, I think I can add a preview and/or direct link to the image (on GitHub and/or cdn).

Which type are you prefer?)

2023-08-10 20:46 UTC, walkxcode commented
CDN.

2023-10-30 09:09 UTC, walkxcode commented
Hi, are you still working on this PR?

2025-01-05 00:20 UTC, walkxcode commented
> [!WARNING]
> The repository has been migrated from `walkxcode` to `homarr-labs`, because I do not have the capacity/time to keep maintaining it. The Homarr team will take over all management and maintenance, whilst keeping all functionality for you, the user, the same. The project will always be usable outside of Homarr itself and breaking changes will not be made. ^Bjorn
>
> Due to a force merge into the main branch, all PRs have unfortunately been affected. We apologize for the inconvenience. Please recreate a new PR from the current `main` branch.
>
> The license and guidelines have changed, so please review them. If you want to help with maintenance, reach out to [homarr-labs@proton.me](mailto:homarr-labs@proton.me).

2025-01-05 00:20 UTC, closed without merging

2025-01-05 01:41 UTC, walkxcode commented
Added with https://github.com/homarr-labs/dashboard-icons/commit/3e30b9fce2fad0e4d4b1749a1b47ac878f6fd5ac