Add wyze and reolink png icon
homarr-labs/dashboard-icons pull request #495
Opened 2023-10-14 00:16 UTC by tracer021

2023-10-30 09:21 UTC, walkxcode requested changes
Please add SVG versions as stated in the contribution guidelines!

2023-10-30 09:56 UTC, tracer021 commented
Updated with svg icons

2024-01-01 11:04 UTC, walkxcode requested changes
Sorry for the late response. These don't look like original SVG's but rather SVG's generated from the PNG files. Would you be able to upload original SVG's?

2025-01-05 00:17 UTC, walkxcode commented
> [!WARNING]
> The repository has been migrated from `walkxcode` to `homarr-labs`, because I do not have the capacity/time to keep maintaining it. The Homarr team will take over all management and maintenance, whilst keeping all functionality for you, the user, the same. The project will always be usable outside of Homarr itself and breaking changes will not be made. ^Bjorn
>
> Due to a force merge into the main branch, all PRs have unfortunately been affected. We apologize for the inconvenience. Please recreate a new PR from the current `main` branch.
>
> The license and guidelines have changed, so please review them. If you want to help with maintenance, reach out to [homarr-labs@proton.me](mailto:homarr-labs@proton.me).

2025-01-05 00:17 UTC, closed without merging